<a href="https://colab.research.google.com/github/almasfiza/ML-DLShow/blob/master/Q1Day3_Almas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#importing the libraries - numpy is use for computations while pandas is used for data analysis
import numpy as np
import pandas as pd

In [3]:
#dataset reading
data = pd.read_csv("Tennis.csv")
print(data.shape)

(14, 5)


In [8]:
data.head(15)

Sr. no.   Outlook Temperature    Wind PlayTennis
0         1     Sunny         Hot    Weak         No
1         2     Sunny         Hot  Strong         No
2         3  Overcast         Hot    Weak        Yes
3         4      Rain        Mild    Weak        Yes
4         5      Rain        Cool    Weak        Yes
5         6      Rain        Cool  Strong         No
6         7  Overcast        Cool  Strong        Yes
7         8     Sunny        Mild    Weak         No
8         9     Sunny        Cool    Weak        Yes
9        10      Rain        Mild    Weak        Yes
10       11     Sunny        Mild  Strong        Yes
11       12  Overcast        Mild  Strong        Yes
12       13  Overcast         Hot    Weak        Yes
13       14      Rain        Mild  Strong         No

In [ ]:
data.tail(10)

In [6]:
#using sklearn to label data
from sklearn import preprocessing

In [7]:
#encodes values from 0 to n-1
le = preprocessing.LabelEncoder()

In [12]:
#Assigning features and label variables Since we cannot use the strings as it is.

Outlook = ['Sunny','Sunny','Overcast','Rain','Rain','Rain','Overcast','Sunny','Sunny','Rain','Sunny','Overcast','Overcast','Rain']

In [13]:
#Converting string labels to encoded numbers
Outlook_encoded = le.fit_transform(Outlook)

In [14]:
#looking at the encoded values
print(Outlook_encoded)

[2 2 0 1 1 1 0 2 2 1 2 0 0 1]


0->Overcast
1->Rain
2->Sunny

Similarly encoding other values

In [15]:
Temperature=['Hot','Hot','Hot','Mild','Cool','Cool','Cool','Mild','Cool','Mild','Mild','Mild','Hot','Mild']
Wind=['Weak','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Weak','Weak','Strong','Strong','Weak','Strong']
PlayTennis=['No','No','Yes','Yes','Yes','No','Yes','No','Yes','Yes','Yes','Yes','Yes','No']

In [16]:
Temperature_encoded = le.fit_transform(Temperature)
Wind_encoded = le.fit_transform(Wind)
PlayTennis_encoded = le.fit_transform(PlayTennis)

In [17]:
#checking the encoded values
print(Temperature_encoded)

[1 1 1 2 0 0 0 2 0 2 2 2 1 2]


0->Cool 1->Hot 2->Mild

In [18]:
print(Wind_encoded)

[1 0 1 1 1 0 0 1 1 1 0 0 1 0]


0->Strong 1-> Weak

In [19]:
print(PlayTennis_encoded)

[0 0 1 1 1 0 1 0 1 1 1 1 1 0]


0->No 1->Yes

Now, comparing the PlayTennis label with all other features

In [21]:
#with Temperature
Temperature_encoded = le.fit_transform(Temperature)
label = le.fit_transform(PlayTennis)
print("Temperature: ",Temperature_encoded)
print("PlayTennis: ",label)

Temperature:  [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
PlayTennis:  [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [24]:
Outlook_encoded = le.fit_transform(Outlook)
label = le.fit_transform(PlayTennis)
print("Outlook: ",Temperature_encoded)
print("PlayTennis: ",label)

Outlook:  [1 1 1 2 0 0 0 2 0 2 2 2 1 2]
PlayTennis:  [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


In [25]:
Wind_encoded = le.fit_transform(Wind)
label = le.fit_transform(PlayTennis)
print("Wind: ",Wind_encoded)
print("PlayTennis: ",label)

Wind:  [1 0 1 1 1 0 0 1 1 1 0 0 1 0]
PlayTennis:  [0 0 1 1 1 0 1 0 1 1 1 1 1 0]


Combining Wind, Temperature and Outlook with PlayTennis in the form of tuples

In [26]:

def merge(Outlook_encoded, Temperature_encoded, Wind_encoded):

  merged_list = tuple(zip(Outlook_encoded, Temperature_encoded, Wind_encoded))
  return merged_list

In [27]:
print(merge(Outlook_encoded,Temperature_encoded,Wind_encoded))

((2, 1, 1), (2, 1, 0), (0, 1, 1), (1, 2, 1), (1, 0, 1), (1, 0, 0), (0, 0, 0), (2, 2, 1), (2, 0, 1), (1, 2, 1), (2, 2, 0), (0, 2, 0), (0, 1, 1), (1, 2, 0))


In [28]:
#import Guassian NB
from sklearn.naive_bayes import GaussianNB

In [29]:
#create a Gaussian classifier
model = GaussianNB() # change ofr Bernouilli and multinomial

In [30]:
#train the model using the training set
model.fit(merge(Outlook_encoded, Temperature_encoded, Wind_encoded),label)

GaussianNB(priors=None, var_smoothing=1e-09)

In [31]:
#Predict for Sunny, Cool, Strong
predicted = model.predict([[2,0,0]])
print("predicted value: ",predicted)

predicted value:  [0]
