# The Machine Learning & Deep Learning Show

## Almasfiza Shaikh 20200620

In [1]:
#importing lib
import numpy as np
import pandas as pd

In [2]:
#importing data
dataset= pd.read_csv("IRIS.csv")

In [3]:
print(dataset.head(5))

   sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa


In [4]:
dataset["species"] = dataset["species"].astype('category')
dataset["Encoded_Species"] = dataset["species"].cat.codes

In [5]:
print(dataset.head(5))

   sepal_length  sepal_width  petal_length  petal_width      species  \
0           5.1          3.5           1.4          0.2  Iris-setosa   
1           4.9          3.0           1.4          0.2  Iris-setosa   
2           4.7          3.2           1.3          0.2  Iris-setosa   
3           4.6          3.1           1.5          0.2  Iris-setosa   
4           5.0          3.6           1.4          0.2  Iris-setosa   

   Encoded_Species  
0                0  
1                0  
2                0  
3                0  
4                0  


In [6]:
#define X & Y
X= dataset.iloc[:,0:4].values

In [7]:
Y= dataset.iloc[:,5].values

In [8]:
#split 
from sklearn.model_selection import train_test_split
X_train, X_test,Y_train, Y_test= train_test_split(X,Y, test_size=0.1)

## Logistics Regression

In [9]:
from sklearn.linear_model import LogisticRegression
logclass= LogisticRegression()
logclass.fit(X_train, Y_train)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:433: FutureWarning: Default solver will be changed to 'lbfgs' in 0.22. Specify a solver to silence this warning.
  FutureWarning)
/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
          intercept_scaling=1, max_iter=100, multi_class='warn',
          n_jobs=None, penalty='l2', random_state=None, solver='warn',
          tol=0.0001, verbose=0, warm_start=False)

In [10]:
Y_pred=logclass.predict(X_test)

In [11]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, Y_pred)

array([[2, 0, 0],
       [0, 6, 1],
       [0, 0, 6]])

## KNN Classifier

In [12]:
from sklearn.neighbors import KNeighborsClassifier
knn= KNeighborsClassifier()
knn.fit(X_train, Y_train)
Y_pred= knn.predict(X_test)

In [13]:
from sklearn.metrics import confusion_matrix
confusion_matrix(Y_test, Y_pred)

array([[2, 0, 0],
       [0, 7, 0],
       [0, 0, 6]])

## Decision Tree

In [23]:

from sklearn.tree import DecisionTreeClassifier


## Complete the code

In [24]:
classifier = DecisionTreeClassifier()
classifier.fit(X_train,Y_train)
Y_pred = classifier.predict(X_test)

### Finding the precision, recall, f1 score using the confusion matrix

In [25]:
from sklearn.metrics import classification_report,confusion_matrix

In [26]:
print(confusion_matrix(Y_test,Y_pred))
print(classification_report(Y_test,Y_pred))

[[2 0 0]
 [0 7 0]
 [0 0 6]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00         6

   micro avg       1.00      1.00      1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



## Random Forest

In [27]:
from sklearn.ensemble import RandomForestClassifier

## Complete the code

In [30]:
regressor = RandomForestClassifier()
regressor.fit(X_train,Y_train)
Y_Pred = regressor.predict(X_test)

/home/nbuser/anaconda3_501/lib/python3.6/site-packages/sklearn/ensemble/forest.py:246: FutureWarning: The default value of n_estimators will change from 10 in version 0.20 to 100 in 0.22.
  "10 in version 0.20 to 100 in 0.22.", FutureWarning)


In [31]:
print(confusion_matrix(Y_test,Y_pred))

[[2 0 0]
 [0 7 0]
 [0 0 6]]


##### Printing the classification report for the confusion matrix printed above.

In [32]:
print(classification_report(Y_test,Y_pred))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00         2
           1       1.00      1.00      1.00         7
           2       1.00      1.00      1.00         6

   micro avg       1.00      1.00      1.00        15
   macro avg       1.00      1.00      1.00        15
weighted avg       1.00      1.00      1.00        15



## Which model performs best accuracy wise?

I have got a score of 1 for KNN, Decision Tree, Random Forest and a score of 0.933 fir Logistic Regression. However, all classification showed an overall high accuracy ranging from 0.9 to 1.0 